name: 'Removing Hello World webserver - EC2'
run-name: ${{ github.actor }} is removing the Hello World webserver onto AWS EC2
on: 
  workflow_dispatch:  

jobs: 
  Terraform-Destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    steps:
      - name: Declare event
        run: echo "The Terraform is manually triggered by a ${{ github.event_name }} event."
        
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2         
    
      - name: Terraform Init
        id: init
        working-directory: ./terraform-method/terraform-files
        run: terraform init
    
      - name: Terraform destroy
        id: destroy
        working-directory: ./terraform-method/terraform-files
        run: terraform destroy --auto-approve

  